replicaCount: 2

image:
  repository: worknitinprajwal/fitness-tracker
  tag: main-0be5172-1782194228
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30000

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"

healthCheck:
  enabled: true
  path: /actuator/health
  port: 8080
